config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lamas do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create, :show] do
      resources :payments, only: [:new, :create]
    end
  end

  get 'reviews', to: 'reviews#index'
  get 'bookings', to: 'bookings#index'
  patch 'bookings', to: 'bookings#update'
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :lama

  validates :date_begin, presence: true
  validates :date_end, presence: true
  validates :user, presence: true
  validates :lama, presence: true

end

app/models/lama.rb
class Lama < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :name, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :price, presence: true

  geocoded_by :full_address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def full_address
    ("#{address}, #{zipcode}")
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :lama
  belongs_to :user

  validates :description, presence: true
  validates :rating, presence: true
  validates :user, presence: true
  validates :lama, presence: true

  validates :user, uniqueness: { scope: :lama }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :photo, PhotoUploader
  has_many :reviews
  has_many :bookings
  has_many :lamas

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo, :photo_cache, :profile_picture, :birthday])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo, :photo_cache, :profile_picture, :birthday])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def after_sign_in_path_for(resource)
    if /sign_in/.match(params[:url]) || /users/.match(params[:url])
      redirect_to root_path
    else
      params[:url]
    end
  end

 private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @lama = Lama.find(params[:lama_id])
    @booking.lama = @lama
    authorize @booking
    if @booking.save
      redirect_to lama_booking_path(@lama.id, @booking.id)
    else
      redirect_to lama_path(@lama.id)
    end
  end

  def show
    @lama = Lama.find(params[:lama_id])
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.state = params[:state]
    authorize @booking
    @booking.save
    redirect_to bookings_path
  end

  private

  def booking_params
    params.permit(:date_begin, :date_end, :user_id, :lama_id, :amount)
  end
end

app/controllers/lamas_controller.rb
require 'pry'

class LamasController < ApplicationController
  before_action :set_lama, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :show
  skip_before_action :authenticate_user!, only: :index

  def index
    logger.debug
    @lamas = policy_scope(Lama) # .where.not(latitude: nil, longitude: nil)
    @lamas = @lamas.where('category ILIKE ?', "%#{params['category']}%").where('name ILIKE ? or sumary ILIKE ?', "%#{params['query']}%", "%#{params['query']}%").order(created_at: :desc) #.where('sumary ILIKE ?', "%#{params['query']}%")

    @markers = @lamas.map do |lama|
      {
        lat: lama.latitude,
        lng: lama.longitude#,
        # infoWindow: { content: render_to_string(partial: "/lamas/map_box", locals: { lama: lama }) }
      }
    end
  end

  def show
    @marker = {
    lat: @lama.latitude,
    lng: @lama.longitude
    }
    @review = Review.new
  end

  def new
    @lama = Lama.new
    authorize @lama
  end

  def create
    @lama = Lama.new(lama_params)
    @lama.user = current_user
    @lama.sumary = "#{@lama.name} #{@lama.description} #{@lama.price} #{@lama.address} #{@lama.zipcode}"
    authorize @lama
    if @lama.save
      redirect_to lama_path(@lama)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @lama.update(lama_params)
    redirect_to lama_path(@lama)
  end

  def destroy
    @lama.destroy
    redirect_to lamas_path
  end

  private

  def set_lama
    @lama = Lama.find(params[:id])
    authorize @lama
  end

  def lama_params
    params.require(:lama).permit(:name, :category, :address, :zipcode, :city, :description, :price, :photo, :photo_cache)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @lamas = policy_scope(Lama).order(created_at: :desc)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
    authorize @booking
  end

  def create
    authorize @booking
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @booking.amount,
      description:  "Payment for teddy #{@booking.lama_id} for order #{@booking.id}",
      currency:     "eur"
    )

    @booking.update(payment: charge.to_json)
    redirect_to lama_booking_path(@booking.lama.id, @booking.id)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_booking_payment_path(@booking)
  end

private

  def set_order
    @booking = Booking.find(params[:booking_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @reviews = policy_scope(Review)
  end

  def create
    @user = User.find(current_user.id)
    @lama = Lama.find(params[:lama_id])
    @review = Review.new(review_params)
    @review.user = @user
    @review.lama = @lama
    authorize @review
    if @review.save
      respond_to do |format|
        format.html { redirect_to lama_path(@lama.id) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'lamas/show' }
        format.js  # <-- idem
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Bookings</h1>

<% if current_user.lamas.first %>
  <div class="container booking-inbox">
    <div class="tabs">
      <a href="#" class="tab active" id="current_tab">Current</a>
      <a href="#" class="tab" id="my_booking_tab">My bookings</a>
    </div>
    <div class="messages" hidden=false id="current_message">
      <ul class="inbox">
        <% q = 0 %>
        <% unless Booking.order('updated_at DESC').first.nil? %>
          <% Booking.order('updated_at DESC').each do |book| %>
            <% if book.lama.user == current_user %>
              <% q += 1 %>
              <li class="message">
                <div class="avatar">
                  <%= cl_image_tag book.user.photo_url, crop: :fill, class:"avatar-large"%>
                </div>
                <div class="message-name">
                  <% if book.state == "Accepted" %>
                    <div class="message-content status accepted indent-icon flexbox-reservation">
                      <i class="fa fa-check-circle"></i>
                      <p><%= book.user.first_name.capitalize %> <%= book.user.last_name.upcase %></p>
                    </div>
                  <% elsif book.state == "Declined" %>
                    <div class="message-content status declined indent-icon flexbox-reservation">
                      <i class="fa fa-times-circle"></i>
                      <p><%= book.user.first_name.capitalize %> <%= book.user.last_name.upcase %></p>
                    </div>
                  <% else %>
                    <div class="message-content status pending indent-icon flexbox-reservation">
                      <i class="fa fa-spinner"></i>
                      <p><%= book.user.first_name.capitalize %> <%= book.user.last_name.upcase %></p>
                    </div>
                  <% end %>
                  <p><%= book.date_begin.first(10) %></p>
                </div>
                <div class="message-body">
                  <div class="message-content">
                    <p><strong><%= book.lama.name %></strong></p>
                    <p>From: <%= book.date_begin.first(10) %>, to: <%= book.date_end.first(10) %></p>
                  </div>
                  <div class="message-content">
                    <p><strong>Amount</strong></p>
                    <p><%= book.amount %> €</p>
                  </div>
                </div>
                <div class="message-status">
                  <% if book.state == "Accepted" %>
                    <div class="message-content status accepted">
                      <p><strong>Accepted</strong></p>
                    </div>
                  <% elsif book.state == "Declined" %>
                    <div class="message-content status declined">
                      <p><strong>Declined</strong></p>
                    </div>
                  <% else %>
                    <div class="status-selection">
                      <%= form_tag bookings_path, method: :patch do %>
                        <%= select_tag :state, options_for_select(['Pending', 'Accepted', 'Declined']), class: "form-control select-status" %>
                        <%= hidden_field_tag 'id', book.id %>
                        <%= button_tag :submit, class: 'btn btn-success validation-status' %>
                      <% end %>
                    </div>
                  <% end %>
                </div>
              </li>
            <% end %>
          <% end %>
        <% end %>
        <% if q == 0 %>
          <li class="message">
            <div class="message-nothing-body">
              <div class="message-content">
                <h4>Nobody booked your lamas yet...</h4>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="messages" hidden=true  id="my_booking_message">
      <ul class="inbox">
        <% unless Booking.where(user: current_user).order('updated_at DESC').first.nil? %>
          <% Booking.where(user: current_user).order('updated_at DESC').each do |book| %>
            <li class="message">
              <div class="message-name">
                <% if book.state == "Accepted" %>
                  <div class="message-content status accepted flexbox-reservation">
                    <p>Reservation</p>
                    <i class="fa fa-check-circle"></i>
                  </div>
                <% elsif book.state == "Declined" %>
                  <div class="message-content status declined flexbox-reservation">
                    <p>Reservation</p>
                    <i class="fa fa-times-circle"></i>
                  </div>
                <% else %>
                  <div class="message-content status pending flexbox-reservation">
                    <p>Reservation</p>
                    <i class="fa fa-spinner"></i>
                  </div>
                <% end %>
                <p><%= book.date_end.first(10) %></p>
              </div>
              <div class="message-body">
                <div class="message-content">
                  <p><strong><%= book.lama.name %></strong></p>
                  <p>From: <%= book.date_begin.first(10) %>, to: <%= book.date_end.first(10) %></p>
                </div>
                <div class="message-content">
                  <p><strong>Amount</strong></p>
                  <p><%= book.amount %> €</p>
                </div>
              </div>
              <div class="message-status">
                <% if book.state == "Accepted" %>
                  <div class="message-content status accepted">
                    <p><strong>Accepted</strong></p>
                  </div>
                <% elsif book.state == "Declined" %>
                  <div class="message-content status declined">
                    <p><strong>Declined</strong></p>
                  </div>
                <% else %>
                  <div class="message-content status pending">
                    <p><strong>Pending</strong></p>
                  </div>
                <% end %>
              </div>
            </li>
          <% end %>
        <% else %>
          <li class="message">
            <div class="message-nothing-body">
              <div class="message-content">
                <h4>You have not booked any lamas...</h4>
                <%= link_to root_path do%>
                  <p>But you can change that!</p>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% else %>
  <div class="container booking-inbox">
    <div class="tabs">
      <a href="#" class="tab active" id="my_booking_tab">My bookings</a>
    </div>
    <div class="messages" id="my_booking_message">
      <ul class="inbox">
        <% unless Booking.where(user: current_user).order('updated_at DESC').first.nil? %>
          <% Booking.where(user: current_user).order('updated_at DESC').each do |book| %>
            <li class="message">
              <div class="message-name">
                <% if book.state == "Accepted" %>
                  <div class="message-content status accepted flexbox-reservation">
                    <p>Reservation</p>
                    <i class="fa fa-check-circle"></i>
                  </div>
                <% elsif book.state == "Declined" %>
                  <div class="message-content status declined flexbox-reservation">
                    <p>Reservation</p>
                    <i class="fa fa-times-circle"></i>
                  </div>
                <% else %>
                  <div class="message-content status pending flexbox-reservation">
                    <p>Reservation</p>
                    <i class="fa fa-spinner"></i>
                  </div>
                <% end %>
                <p><%= book.date_end.first(10) %></p>
              </div>
              <div class="message-body">
                <div class="message-content">
                  <p><strong><%= book.lama.name %></strong></p>
                  <p>From: <%= book.date_begin.first(10) %>, to: <%= book.date_end.first(10) %></p>
                </div>
                <div class="message-content">
                  <p><strong>Amount</strong></p>
                  <p><%= book.amount %> €</p>
                </div>
              </div>
              <div class="message-status">
                <% if book.state == "Accepted" %>
                  <div class="message-content status accepted">
                    <p><strong>Accepted</strong></p>
                  </div>
                <% elsif book.state == "Declined" %>
                  <div class="message-content status declined">
                    <p><strong>Declined</strong></p>
                  </div>
                <% else %>
                  <div class="message-content status pending">
                    <p><strong>Pending</strong></p>
                  </div>
                <% end %>
              </div>
            </li>
          <% end %>
        <% else %>
          <li class="message">
            <div class="message-nothing-body">
              <div class="message-content">
                <h4>You have not booked any lamas...</h4>
                <%= link_to root_path do%>
                  <p>But you can change that!</p>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>


<%= content_for :after_js do %>
  <%= javascript_pack_tag "index" %>
<%end%>

app/views/bookings/show.html.erb
<div class="container container-resized">
<h1>Booking</h1>
  <div class="card-booking">
    <div>
      <div class="text-center">
        <h4>Your booking details</h4>
      </div>
      <div class="booking-infos">
        <p><strong>Lama:</strong> <%= @booking.lama.name %></p>
        <p><strong>From:</strong> <%= @booking.date_begin %></p>
        <p><strong>To:</strong> <%= @booking.date_end %></p>
        <p><strong>Address:</strong> <%= @booking.lama.address %></p>
        <p><strong>Amount:</strong> <%= @booking.amount %>€</p>
      </div>
      <% if @booking.payment %>
      <div class="text-center">
        <div class="alert alert-success">Your booking is confirmed !</div>
      </div>
      <% else %>
      <div class="text-center">
        <%= link_to "Confirm your booking", new_lama_booking_payment_path(params[:lama_id], @booking), class: "btn btn-primary" %>
      </div>
      <% end %>
    </ul>
    </div>
  </div>
</div>

app/views/lamas/destroy.html.erb
<h1>Lamas#destroy</h1>
<p>Find me in app/views/lamas/destroy.html.erb</p>

app/views/lamas/edit.html.erb
<h1>Edit lama's informations</h1>

<div class="container edit-lama-form">
  <%= simple_form_for @lama do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.input :category, collection: ['Fighter', 'Runner', 'Hugger', 'Party'] %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :zipcode %>
    <%= f.input :price %>
    <div class="text-right">
      <%= f.button :submit, class: 'btn btn-primary' %>
    </div>
  <% end  %>
</div>

app/views/lamas/index.html.erb
<h1>Listing lamas</h1>

<div class="container">
  <div class="cards">
    <% a, b = 0, 2 %>
    <% unless @lamas.first.nil? %>  <!-- || params['query'] == ' ' || params['query'].nil? ||params['query'].size == 0  -->
      <% while @lamas.size > b - 2 %>
        <div class='row'>
          <% @lamas.each do |lama| %>
            <%= link_to lama_path(lama), class: "card-link" do %>
              <div class="card " style="background-image: linear-gradient(-225deg, rgba(256,0,0,0.4) 0%, rgba(0,0,0,0.3) 50%), url('');">  <!-- cl_image_path lama.photo, gravity: :face -->
                <h4><%= lama.name %></h4>
              </div>
            <% end %>
          <% end %>
        </div>
        <% a += 3 %>
        <% b += 3 %>
      <% end %>
    <div
      id="map"
      style="width: 100%;
      height: 600px;"
      data-markers="<%= @markers.to_json %>"
    >
    </div>
    <% else %>
      <h2> Result not founds for the current request </h2>
        <ul>
          <li> Catégorie : <%= params['category'] %> </li>
          <li> Query parameter : <%= params['query'] %> </li>
        </ul>
    <% end %>
  </div>
</div>

app/views/lamas/new.html.erb
<h1>Add a lama</h1>

<div class="container new-lama-form">
  <%= simple_form_for @lama do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.input :category, collection: ['Fighter', 'Runner', 'Hugger', 'Party'] %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :zipcode %>
    <%= f.input :price %>
    <div class="text-right">
      <%= f.button :submit, class: 'btn btn-primary' %>
    </div>
  <% end  %>
</div>

app/views/lamas/show.html.erb
<div class="links">
  <% if policy(@lama).edit? %>
    <%= link_to edit_lama_path(@lama) do %>
      <i class="fa fa-edit"></i>
    <% end %>
  <% end %>
  <% if policy(@lama).destroy? %>
    <%= link_to lama_path(@lama), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="fa fa-trash"></i>
    <% end %>
  <% end %>
</div>


<h1><%= @lama.name %></h1>
<div class="container container-resized">
  <div class="description">
    <div class="card-show" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.4) 0%, rgba(256,0,0,0.3) 50%), url('');"> <!-- cl_image_path @lama.photo, crop: :fill -->
    </div>
    <div class="lama-infos">
      <div>
        <p><strong>Name: </strong><%= @lama.name %></p>
      </div>
      <div>
        <p><strong>Category: </strong><%= @lama.category %></p>
      </div>
      <div>
        <p><strong>Description: </strong><%= @lama.description %></p>
      </div>
      <div>
        <p id="price-per-day"><strong>Price: </strong><%= @lama.price %>€ per day</p>
      </div>
      <div>
        <p><strong>Address: </strong><%= @lama.address %> <%= @lama.zipcode %></p>
      </div>
    </div>
  </div>

  <div>
    <% Booking.where(lama: @lama).each do |booking| %>
    <input type="hidden" class="booking_date" value="<%= booking.date_begin %>"/>
    <input type="hidden" class="booking_date" value="<%= booking.date_end %>"/>
    <% end %>
  </div>

  <% unless @lama.user == current_user %>
    <div class="reservation">
      <%= form_tag(lama_bookings_path(@lama)) do %>
        <div class="dates form-group">
          <div class="">
            <%= label_tag :start_time, 'Check in' %>
            <div class="input-group date input-date" id="datetimepicker1">
              <input type='text' name="date_begin" class="form-control" id='datetimepicker3' />
            </div>
          </div>
          <div class="">
            <%= label_tag :end_time, 'Check out' %>
            <div class="input-group date input-date" id="datetimepicker2">
              <input type='text' name="date_end" class="form-control" id='datetimepicker4' />
            </div>
          </div>
          <div>
            <%= hidden_field_tag 'amount', '0' %>
          </div>
        </div>
        <div class="rest-div">
          <div class="calculated-price">
          </div>
          <div class="text-right">
            <%= button_tag 'Request to book', type: :submit, class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>


  <div class="reviews form-group">
    <% unless current_user == @lama.user %>
      <h4>New review</h4>
      <%= render 'reviews/form', lama: @lama, review: @review %>
    <% end %>
    <% if @lama.reviews.blank? %>
      <div class="reviews2">
        <p>Be the first to leave a review for <%= @lama.name %></p>
      </div>
    <% else %>
      <h4>Reviews</h4>
      <div class="reviews2">
        <% @lama.reviews.order('updated_at DESC').each do |review| %>
          <%= render 'reviews/show', review: review %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div
    id="lamap"
    style="width: 100%;
    height: 600px;"
    data-marker="<%= @marker.to_json %>"
  ></div>
</div>


<%= content_for :after_js do %>
  <%= javascript_pack_tag "show" %>
<%end%>

app/views/lamas/update.html.erb
<h1>Lamas#update</h1>
<p>Find me in app/views/lamas/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'animal.png'%>

    <title>Rent a Lama</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %>

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %> <!-- add this line -->
    <%= yield :after_js %>
  </body>
</html>

app/views/payments/new.html.erb
<div class="container container-resized" style="text-align:center;">
<h1>Purchase <%= @booking.lama.name %></h1>
<%= form_tag lama_booking_payments_path(@booking) do %>
  <div class="payment">
    <article>
      <label class="review">
        <span>Amount: <%= @booking.amount %>€</span>
      </label>
    </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="Purchase <%= @booking.lama.name %>"
    data-email="<%= current_user.email %>"
    data-description="Great choice"
    data-amount=""
    data-currency="€"></script>
  </div>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "animal.png", height: 45 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Your reviews", reviews_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Create your announce", new_lama_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo_url, crop: :fill, class:"avatar"%>
          <%#= image_tag "#", height: 50, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <li>
              <%= link_to "Edit profile" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>